### ISSUE TITLE
Importer fails with some .gpl files

### ISSUE THREAD

**Issue by turbohz** [EricEzaM/godot-color-palette#1]
Hi, 

I was trying to use this add-on with the following palette, generated with GIMP 2.10.18,  but some colors were lost, not parsed correctly. 

The issue seems to be with the test for lines that start with numbers.
Apparently, valid palette entries can start with whitespace. 

See for instance:

```
GIMP Palette
Name: [famicube]
Columns: 16
#
  0   0   0	Index 0
224  60  40	Index 1
255 255 255	Index 2
215 215 215	Index 3
168 168 168	Index 4
123 123 123	Index 5
 52  52  52	Index 6
 21  21  21	Index 7
 13  32  48	Index 8
 65  93 102	Index 9
```

Notice also that after the entry there's a name (in this case it seems autogenerated, but perhaps you can manually fill them in?). It comes after a tab `\t`. 

The format seems to be:

```
[spaces (optional)] R [spaces] G [spaces] B [tab] name
```

I made a fork of this repo, and created a fix which properly imports the `.gpl` file I had.

https://github.com/turbohz/godot-color-palette/commit/15fcf7f2463eff14e013583b4e2069a688865075

Would you like me to submit a pull request? 

Cheers.

**Comment by EricEzaM** [comment]
Hey, thanks for that @turbohz, and sorry for not seeing this sooner. I don't think I got a notification for this even though I have them turned on.

Feel free to submit a PR and I'll merge :)
