### ISSUE TITLE
Does the system accept alpha values?

### ISSUE THREAD

**Issue by BlotoPK** [EricEzaM/godot-color-palette#6]
Hi. It seems that I cannot store colors with alpha values != 255.
I'm using a 3.x win version of Godot.

**Comment by EricEzaM** [comment]
Yes that is the case, and I think it is correct. The GPL format does not seem to store alpha values - see source code from GIMP here: https://gitlab.gnome.org/GNOME/gimp/-/blob/gimp-2-10/app/core/gimppalette-load.c#L39
